=== dfmode/DataFormats/3/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
	xmlns:tns="http://example.org/xsd"
	targetNamespace="http://example.org/xsd"
	elementFormDefault="qualified"
>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="https://www.w3.org/2009/01/xml.xsd"/>
	<xs:element name='universities'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='tns:university' minOccurs='1' maxOccurs='unbounded'/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="person">
		<xs:sequence>
			<xs:element name="name">
				<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute ref="xml:lang" use="required"></xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
			</xs:element>
			<xs:element name="birthday" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="student" type="tns:person"/>
	<xs:element name="teacher" type="tns:person"/>
	<xs:element name="teachers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:teacher" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="students">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:student" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="names">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute ref="xml:lang" use="required"></xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="course">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:names"/>
				<xs:element name="code" type="xs:string"/>
				<xs:element name="websites">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="website" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="tns:students"/>
				<xs:element ref="tns:teachers"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="faculty">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:names"/>
				<xs:element name="websites">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="website" type="xs:anyURI" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="courses">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="tns:course" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="tns:students"/>
				<xs:element ref="tns:teachers"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="university">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:names"/>
				<xs:element name="websites">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="website" type="xs:anyURI" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="faculties">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="tns:faculty" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dfmode/DataFormats/3/xml/data/data-1.xml
<?xml version="1.0" encoding="utf-8"?>
<u:universities
	xmlns:u="http://example.org/xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema-1.xsd">
	<u:university>
		<u:names>
			<u:name xml:lang="en-EN">
                    Charles University
                </u:name>
			<u:name xml:lang="cs-CZ">
                    Karlova univerzita
                </u:name>
		</u:names>
		<u:websites>
			<u:website>
                    http://www.cuni.cz
                </u:website>
			<u:website>
                    https://www.cuni.cz/uken-1.html
                </u:website>
		</u:websites>
		<u:faculties>
			<u:faculty>
				<u:names>
					<u:name xml:lang="en-EN">
                            Faculty of Arts
                        </u:name>
					<u:name xml:lang="cs-CZ">
                            Filozofická fakulta
                        </u:name>
				</u:names>
				<u:websites>
					<u:website>
                            http://www.ff.cuni.cz
                        </u:website>
					<u:website>
                            https://www.ff.cuni.cz/en
                        </u:website>
				</u:websites>
				<u:courses>
					<u:course>
						<u:names>
							<u:name xml:lang="en-EN">
                                    Historical Development of Europe in Comparative Perspective
                                </u:name>
							<u:name xml:lang="cs-CZ">
                                    Historický vývoj Evropy v komparativní perspektivě
                                </u:name>
						</u:names>
						<u:code>
                                AHE110018
                            </u:code>
						<u:websites>
							<u:website>
                        	https://is.cuni.cz/studium/predmety/index.php?id=ea629e3e972f695ebb7e4383e410feda&amp;tid=&amp;do=predmet&amp;kod=AHE110018
                        </u:website>
						</u:websites>
						<u:students>
							<u:student>
								<u:name>
                                        Karel Matej Čech-Chod
                                    </u:name>
								<u:birthday>
                                        1860-02-21
                                    </u:birthday>
							</u:student>
							<u:student>
								<u:name>
                                        Dia Líšková
                                    </u:name>
								<u:birthday>
                                        2000-05-27
                                    </u:birthday>
							</u:student>
							<u:student>
								<u:name >
                                        Josef Uřídil
                                    </u:name>
								<u:birthday>
                                        1985-11-19
                                    </u:birthday>
							</u:student>
						</u:students>
						<u:teachers>
							<u:teacher>
								<u:name >
                                        Mgr. Jaroslav Mira Ph.D.
                                    </u:name>
								<u:birthday>
                                        1968-08-21
                                    </u:birthday>
							</u:teacher>
						</u:teachers>
					</u:course>
					<u:course>
						<u:names>
							<u:name xml:lang="en-EN">
                                    Czech Literature of Older Times - Lecture
                                </u:name>
							<u:name xml:lang="cs-CZ">
                                    Starší česká literatura - přednáška
                                </u:name>
						</u:names>
						<u:code>
                                ABO600601
                            </u:code>
						<u:websites>
							<u:website>
                          https://is.cuni.cz/studium/predmety/index.php?id=ea629e3e972f695ebb7e4383e410feda&amp;tid=&amp;do=predmet&amp;kod=ABO600601
                        </u:website>
						</u:websites>
						<u:students>
							<u:student>
								<u:name >
                                        Karel Matej Čech-Chod
                                    </u:name>
								<u:birthday>
                                        1860-02-21
                                    </u:birthday>
							</u:student>
							<u:student>
								<u:name >
                                        Petr Kopecký
                                    </u:name>
								<u:birthday>
                                        1969-04-20
                                    </u:birthday>
							</u:student>
						</u:students>
						<u:teachers>
							<u:teacher>
								<u:name >
                                        Mgr. Marie Škaropová Ph.D.
                                    </u:name>
								<u:birthday>
                                        1957-09-10
                                    </u:birthday>
							</u:teacher>
						</u:teachers>
					</u:course>
				</u:courses>
				<u:students>
					<u:student>
						<u:name >
                                Karel Matej Čech-Chod
                            </u:name>
						<u:birthday>
                                1860-02-21
                            </u:birthday>
					</u:student>
					<u:student>
						<u:name >
                                Dia Líšková
                            </u:name>
						<u:birthday>
                                2000-05-27
                            </u:birthday>
					</u:student>
					<u:student>
						<u:name >
                                Petr Kopecký
                            </u:name>
						<u:birthday>
                                1969-04-20
                            </u:birthday>
					</u:student>
				</u:students>
				<u:teachers>
					<u:teacher>
						<u:name >
                                Mgr. Marie Škaropová Ph.D.
                            </u:name>
						<u:birthday>
                                1957-09-10
                            </u:birthday>
					</u:teacher>
					<u:teacher>
						<u:name >
                                Mgr. Jaroslav Mira Ph.D.
                            </u:name>
						<u:birthday>
                                1968-08-21
                            </u:birthday>
					</u:teacher>
				</u:teachers>
			</u:faculty>
		</u:faculties>
	</u:university>
	<u:university>
		<u:names>
			<u:name xml:lang="en-EN">
                    Czech Technical University in Prague
                </u:name>
			<u:name xml:lang="cs-CZ">
                    České vysoké učení technické v Praze
                </u:name>
		</u:names>
		<u:websites>
			<u:website>
                    https://www.cvut.cz
                </u:website>
		</u:websites>
		<u:faculties>
			<u:faculty>
				<u:names>
					<u:name xml:lang="en-EN">
                            Faculty of Nuclear Sciences and Physical Engineering
                        </u:name>
					<u:name xml:lang="cs-CZ">
                            Fakulta jaderná a fyzikálně inženýrská
                        </u:name>
				</u:names>
				<u:websites>
					<u:website>
                            https://www.fjfi.cvut.cz/cz/
                        </u:website>
					<u:website>
                            https://www.fjfi.cvut.cz/en/
                        </u:website>
				</u:websites>
				<u:courses>
					<u:course>
						<u:names>
							<u:name xml:lang="cs-CZ">
                                    Elektřina a magnetismus
                                </u:name>
						</u:names>
						<u:code>
                                02ELMA
                            </u:code>
						<u:websites>
							<u:website>
                            https://bilakniha.cvut.cz/cs/predmet11279205.html#gsc.tab=0
                        </u:website>
						</u:websites>
						<u:students>
							<u:student>
								<u:name>
                                        Alena Výbušná
                                    </u:name>
								<u:birthday>
                                        1986-04-26
                                    </u:birthday>
							</u:student>
						</u:students>
						<u:teachers>
							<u:teacher>
								<u:name >
                                        doc. Ing. Jiří Hrivnák Ph.D.
                                    </u:name>
								<u:birthday>
                                        1968-08-20
                                    </u:birthday>
							</u:teacher>
						</u:teachers>
					</u:course>
				</u:courses>
				<u:students>
					<u:student>
						<u:name>
                                Alena Výbušná
                            </u:name>
						<u:birthday>
                                1986-04-26
                            </u:birthday>
					</u:student>
				</u:students>
				<u:teachers>
					<u:teacher>
						<u:name >
                                doc. Ing. Jiří Hrivnák Ph.D.
                            </u:name>
						<u:birthday>
                                1968-08-20
                            </u:birthday>
					</u:teacher>
				</u:teachers>
			</u:faculty>
			<u:faculty>
				<u:names>
					<u:name xml:lang="en-EN">
                            Faculty of Transportation Sciences
                        </u:name>
					<u:name xml:lang="cs-CZ">
                            Fakulta dopravní
                        </u:name>
				</u:names>
				<u:websites>
					<u:website>
                            https://www.fd.cvut.cz/cz/
                        </u:website>
				</u:websites>
				<u:courses>
					<u:course>
						<u:names>
							<u:name xml:lang="cs-CZ">
                                    Dopravní psychologie
                                </u:name>
						</u:names>
						<u:code>
                                15DPLG
                            </u:code>
						<u:websites>
							<u:website>
                            https://www.fd.cvut.cz/studenti/predmet-detail.html?kod=615DPLG
                        </u:website>
						</u:websites>
						<u:students>
							<u:student>
								<u:name>
                                        John Domiešavač
                                    </u:name>
								<u:birthday>
                                        1992-04-17
